// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoPo_BCZWWKJJ0ggQhQe2VKMcamayuL6g',
    appId: '1:304149155552:web:06866801fa55f16a8e4a85',
    messagingSenderId: '304149155552',
    projectId: 'videon-8655',
    authDomain: 'videon-8655.firebaseapp.com',
    storageBucket: 'videon-8655.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzKLL2ECFNv2UZDfI-GVLeDrqdWssrJUk',
    appId: '1:304149155552:android:38d85c76db8ea1638e4a85',
    messagingSenderId: '304149155552',
    projectId: 'videon-8655',
    storageBucket: 'videon-8655.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB51jbARxcNQubI7MWsFZrKPCIw4RcTDnQ',
    appId: '1:304149155552:ios:ee21f009a355f8268e4a85',
    messagingSenderId: '304149155552',
    projectId: 'videon-8655',
    storageBucket: 'videon-8655.firebasestorage.app',
    iosBundleId: 'com.example.videon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB51jbARxcNQubI7MWsFZrKPCIw4RcTDnQ',
    appId: '1:304149155552:ios:ee21f009a355f8268e4a85',
    messagingSenderId: '304149155552',
    projectId: 'videon-8655',
    storageBucket: 'videon-8655.firebasestorage.app',
    iosBundleId: 'com.example.videon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoPo_BCZWWKJJ0ggQhQe2VKMcamayuL6g',
    appId: '1:304149155552:web:83e7f5fff2d75c458e4a85',
    messagingSenderId: '304149155552',
    projectId: 'videon-8655',
    authDomain: 'videon-8655.firebaseapp.com',
    storageBucket: 'videon-8655.firebasestorage.app',
  );
}
